name: cv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.1.1
  - numpy=1.22.3
  - pandas=1.4.2
  - pillow=7.1.2
  - python=3.8.13
  - pytorch=1.8.1
  - scipy=1.7.3
  - torchvision=0.9.1
  - pip:
    - mmcv==1.5.2
    - pytorch-lightning==1.2.3
    - segmentation-models-pytorch==0.2.0
    - timm==0.4.12
prefix: /home/usrname/miniconda3/envs/cv
